### ISSUE TITLE
[FEATURE] manage.py

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#259]
**Explanation**
After some trial deployment headaches, I am manually running app.app_context() and using the db models and sql alchemy to push basic tables to the app in mysql.  This is time consuming and we can do what the industry does and create a default manage.py that will add everything we need automatically by default, as well as provide a management and migration interface.

**Brief**
- [x] #271
- [x] from app import create_app
- [x] app = create_app()
- [x] from app import db
- [x] import all models from app.db.models
- [x] create a create_all method that creates all basic columns and tables
- [x] create a create_defaults method that creates basic roles, admin user, and role members, takes password and sha encrypts

**Comment by stuart909** [comment]
I will keep this ticket open until I feel we should create another task to enhance the manage.py.  Let's hold until we fix some bugs.

**Comment by stuart909** [comment]
create all creates most basic items.  Just need to establish a working user and usermembers code.  The test I did failed.
