### ISSUE TITLE
[FEATURE] Paginate API

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#315]
**Explanation**
We will need to create a pagination API and implement it on all the routes and the views that load links or items.

**Brief**
```
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc
from flask_sqlalchemy.pagination import Pagination

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
db = SQLAlchemy(app)

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)

@app.route('/items/<int:page>')
def items(page):
    # Query the database for a list of items
    items = Item.query.order_by(desc(Item.id)).all()

    # Create a pagination object with the query results
    pagination = Pagination(query=items, page=page, per_page=10)

    # Render the template and pass in the pagination object
    return render_template('items.html', pagination=pagination)
```

**Outline**
- [ ] Create paginate API in app.db.util package
- [ ] Implement pagination on views that render link lists or item lists
- [ ] import app.db.util paginate function and paginate all routes that render link lists or item lists

**Comment by stuart909** [comment]
Additionally, we need functions in our API that allow us to sort by newest or oldest date.

**Comment by stuart909** [comment]
branch 320-feature-flask-commonmark contains the app.db.util.paginate() fix

It's been merged to branch dev-B1.1

**Comment by stuart909** [comment]
- I fixed the paginate method.  It was always returning page 1.  It should now return the correct page.
- I also added a macro to use the paginate viewer for oneDiv forms.  It was implemented in products.html
