### ISSUE TITLE
[FEATURE] Flask-Commonmark

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#320]
**Explanation**
After some basic research, I have decided we need to implement mark-down language in our text editors.  This is actually remarkably easy to implement.

**Brief**
We first need to install Flask-Commonmark and all dependencies in our environment, and also add the Flask-Commonmark to the requirements.txt for our project.  We then have to bring in the commonmark application and attach it to our app in the app.init.  We then have to call upon commonmark in any view that is rendering text from one of our content editors that stores the long strings in the database.

**Outline**
- [x] pip install Flask-Commonmark  and update the requirements.txt
- [x] import the Flask-Commonmark library in app.init and attach it to the app
- [x] implement the commonmark tag on all templates rendering text editor content.
