### ISSUE TITLE
[FEATURE] Company Editor

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#335]
**Explanation**
The company editor was hidden for the admin and is missing the member adder.  I also don't like the placement of the editor, as it is in the user profile section.  We should move the company editor into a proper company editor page in a nav bar or a tools bar for admin.  The re-enable the company view in profiles if the user is a member of a company.

**Brief**
Make a proper company editor page.  Remove the editor from profiles.  Finally, re-enable the company view if the user is a member of the company.  This is a granular permissions addition.

**Outline**
- [x] Move company editor to a tool bar instead of profiles section.
- [x] Remove the company editor from profiles completely
- [x] Re-enable company view if user is a member of a company
- [x] double check the granular permissions
- [x] ensure company view is properly setup in admin
