### ISSUE TITLE
[FEATURE] Customer Editor

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#336]
**Explanation**
We need to go ahead and add a customer editor in the admin tool bar.  We have a customer ORM but we haven't finished linking up all of the ORM due to the complexities of customers being both users and companies.  Let's go ahead and add the customer editor.  Any user or company that had an order would be a customer.  We need to be able to edit customers and add customers based on orders.  There should also be a placeholder link, for now, that links the order editor.

**Brief**
Need a customer editor.

**Outline**
- [ ] Finish the customer ORM
- [ ] Add the customer editor page
- [ ] Add the customer editor page to the admin tool bar
- [ ] create the order editor link for future order editor menu

**Comment by jkcswd** [comment]
336-customer-editor-james
