### ISSUE TITLE
[FEATURE] Order Editor

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#337]
**Explanation**
A proper order editor is still on the roadmap.  This is not the same as a shopping cart.  We are making a CRM.  We do not handle purchases, we simple have orders that are entered manually with our CRM or injected from a shopping system.  The order system is for internal employees and customers to be able to properly track orders and contracts so better service can be provided.

**Brief**
Create an order editor / viewer

**Outline**
- [x] Finish the order ORM
- [x] Create an order editor / viewer that resided in an admin tool bar
- [x] Create an order viewer, similar to company viewer, that exists in the user profile.  Users should be able to see their orders
- [ ] double check granular permissions.
- [ ] add order to the admin view
