### ISSUE TITLE
[FEATURE] Profile Event viewer

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#338]
**Explanation**
Users should be able to see upcoming events in their profile that they have been added to.

**Brief**
Make an event viewer in the user profile section

**Outline**
- [x] Create the event viewer in the user profile section.  This is a read only view for now.
- [x] Make sure that the calendar can add users and or groups to the event.
- [ ] Update ORM so events have role members.  Permissions are is_role OR user_permission

**Additional Context**
When an event is made in Calendar, anyone in the calendar's assigned group can see the event in the calendar/events section.  What this issue does is make the event visible in a user's profile if they can see the event.  Not everyone will have access to the Calendar section, IE, customers.  However, if a customer is scheduled an event to speak with technical support, the customer's profile should be able to see that event in the profile.
