### ISSUE TITLE
Messenger Socket I/O

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#367]
Create Messenger API as Flask-SocketIO library

### Description
Create a Flask-SocketIO library to handle messaging functionality for our app. This library should be designed to be consumed by other parts of the app, such as the Flask routes and templates.

### Tasks
- [ ] Create a new file `messenger.py` in the `app/util` directory
- [ ] Import `Flask-SocketIO` and create a `SocketIO` instance
- [ ] Create a `Messenger` class with methods for handling messaging functionality (e.g. sending and receiving messages)
- [ ] Define `Flask-SocketIO` routes for handling messaging functionality
- [ ] Create a `connect` and `disconnect` event handlers for managing client connections
- [ ] Implement the `Messenger` class methods to interact with the `Flask-SocketIO` routes
