### ISSUE TITLE
[TASK] generate sitemap based off of routes and robot

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#381]
### Description
We need to update our sitemap.xml to include only routes that are allowed according to our robots.txt file. To accomplish this, we need to:
- Get all routes from our `blueprints` variable (a list of Flask blueprints)
- Evaluate each route against the `robots.txt` file to determine if it is allowed
- Only include permitted routes in the `sitemap.xml` file

### Tasks
- [ ] Create a Python script to extract routes from `blueprints` and evaluate them against `robots.txt`
- [ ] Modify the script to output a list of permitted routes
- [ ] Update the sitemap.xml generation process to use only permitted routes

### Additional Information
- Our Flask app is hosted on GitHub at https://github.com/your-organization/your-repo
- The `blueprints` variable can be found in the `app.routes` module
- The `robots.txt` file can be found in the root directory of the app
- The `sitemap.xml` file can be found in the root directory of the app
