### ISSUE TITLE
[FEATURE] Create the Autocomplete route

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#384]
### Description
We need to create a Flask route to handle autocomplete requests for the search field. This route will take a query string as input and return a JSON response with possible search results.

### Tasks
- [ ] Create a new Flask route for the autocomplete functionality
- [ ] Retrieve the query string from the AJAX request parameters
- [ ] Perform a SQL query to find possible search results based on the query string
- [ ] Convert the search results to a JSON format using the `jsonify()` function
- [ ] Return the JSON response to the AJAX request

### Acceptance Criteria
- The autocomplete route is created and returns a JSON response with possible search results based on the input query string.
