### ISSUE TITLE
Create ORM to Store Messages

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#388]
### Description
Create an ORM to store messages sent and received in the messenger component of our app. The ORM should include columns for the message content, user information, group information, and date/time information.

### Tasks
- [x] Create a new file `message.py` in the `app/models` directory
- [x] Define a `Message` class with properties for the message content, user information, group information, and date/time information
- [x] Use the `Flask-SQLAlchemy` extension to define a database table for storing messages
- [ ] Define methods in the `Message` class for creating, updating, and deleting messages in the database
- [ ] Update the `Messenger` class in `app/util/messenger.py` to use the `Message` ORM to store messages sent and received
- [ ] Test the `Message` ORM by sending and receiving messages and verifying that they are stored correctly in the database

**Comment by stuart909** [comment]
created in origin/message
